@eAppoinmentServer.WebAPI_HostAddress = http://localhost:5191

POST http://localhost:5191/api/Auth/Login
Accept: application/json
Content-Type:application/json

{
   "userNameOrEmail":"admin",
   "password":"1"
}

###
